# Configuration settings for the agent framework

# Model defaults
models:
  default_provider: openai
  default_model: gpt-4
  default_temperature: 0.7
  max_tokens: null
  streaming: false

# Tool settings
tools:
  enable_all: false
  default_tools:
    - calculator
    - datetime
    - weather
  restricted_tools:
    - write_file
    - execute_code

# Agent settings
agents:
  max_iterations: 10
  enable_memory: true
  memory_type: in_memory
  verbose: false

# Workflow settings
workflows:
  max_steps: 100
  enable_visualization: true
  checkpoint_interval: 10

# Logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/agent_framework.log

# Performance
performance:
  request_timeout: 60
  max_concurrent_agents: 5
  cache_responses: true
  cache_ttl: 3600